Metrics/CyclomaticComplexity:
  Excluded:
    - src/generated/**
    - src/generated/**/*

Naming/QueryBoolMethods:
  Excluded:
    - src/generated/**
    - src/generated/**/*

Lint/Typos:
  Excluded:
    - src/generated/**
    - src/generated/**/*

